# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Oh So Hyun
title: All About Sohyun!
email: osohyun0224@naver.com
phone: +82)010-6775-6976
website: https://github.com/osohyun0224

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: osohyun0224
instagram_username: o._.sohyun24
youtube_username: soom

# Additional icon links
additional_links:
- title: Only sohyun's place
  icon: fas fa-globe
  url: https://www.instagram.com/o._.sohyun224
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Sohyun and I'm a student in Hallym University. My major is Computer Engineering. So I am very interested in programming. I will try to become a programmer who can slove any problem well.

  My dream is  in: <mark>Computer Teacher! </mark>
 

content:
  - title: sohyun's mentoring! # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: sohyun's Java Study
        link: https://treasure-tartan-495.notion.site/Java-75fd1f8b371a41bb8d603a8f62ca55e6
        # link_text: Project Website
        quote: >
          Please take a look at my lecture materials and give me feedback for better instruction!
        description: | # this will include new lines to allow paragraphs
          The reason why I'm a mentor is that I can study Java once again in detail while teaching myself. I am interested in teaching and I lead the class well because the student's achievements are good. l also prepare harder for the class. I expect my students to get good grades.


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Internship at Daesung
        link: https://www.mimacstudy.com/main/main.ds
        # link_text: https://www.mimacstudy.com/main/main.ds
        sub_title: An editorial Intern at the Mathematics Institute in Daesung
        caption: November 2019 - Present
        quote: >
          Although I lack the qualifications, I was able to work as editing intern at a famous academy.
        description: | # this will include new lines to allow paragraphs
          I had meticulousness, diligence, and sincerity while editing class materials for 3 years. Also, I had a sense of closeness by grading studnet's assignments, and they got better. This internship is the reason why I have a dream of becoming a teacher.
 
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Hallym University
        caption: 2020-2023
        sub_title: Computer Engineering
        quote: >
          Hallym University is located in Chuncheon, Republic of  Korea.
        description: | # this will include new lines to allow paragraphs
          In the last three years of school, I have done various activities in school. I worked for the students in the student council and also mixed songs in hip-hop clubs. Also, I did my best to do educational volunteer work for a year. I am aiming to graduate early by studying hard for my department.


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Write Blog
      - Listening to music
      - Knitting
      



# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
